version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.{{PHP_VERSION}}
        image: {{PROJECT}}-php:{{PHP_VERSION}} 
        container_name: {{PROJECT}}-app
        working_dir: /var/www
        restart: unless-stopped
        tty: true
        volumes:
            - /tmp:/tmp
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network-{{PROJECT}}
{% if DB_MODE == "shared" %}
            - {{SHARED_DB_NETWORK}}
{% endif %}            
        depends_on:
{% if DB_MODE == "local" %}
            - db
{% endif %}

    worker:
        image: {{PROJECT}}-php:{{PHP_VERSION}}
        container_name: {{PROJECT}}-worker
        working_dir: /var/www
        restart: unless-stopped
        command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network-{{PROJECT}}
{% if DB_MODE == "shared" %}
            - {{SHARED_DB_NETWORK}}
{% endif %}  
        depends_on:
            - app
            - redis

    web:
        image: nginx:latest
        container_name: {{PROJECT}}-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/snippets/:/etc/nginx/snippets/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - app-network-{{PROJECT}}
            - nginxproxyman
{% if DB_MODE == "shared" %}
            - {{SHARED_DB_NETWORK}}
{% endif %}            
        depends_on:
            - app

{% if DB_MODE == "local" %}
    db:
        image: "{{DB_IMAGE}}"
        container_name: {{PROJECT}}-db
        environment:
{% if DB_TYPE == "mysql" %}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}_local_user
            MYSQL_PASSWORD: ${DB_PASSWORD}            
            MYSQL_DATABASE: {{PROJECT}}_local
            TZ: Europe/Moscow
{% else %}            
            POSTGRES_USER: ${DB_USERNAME}_local_user
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: {{PROJECT}}_local
            TZ: Europe/Moscow
{% endif %}
        volumes:
            - "{{DB_VOLUME}}:/var/lib/{{DB_STORAGE_PATH}}"        
        ports:
            - 127.0.0.1:33386:3306 # ❗ dev only
            - 127.0.0.1:5482:5432  # ❗ dev only
        networks:
            - app-network-{{PROJECT}}
        mem_limit: 512m # RAM лимит
        memswap_limit: 1g # swap лимит            
{% endif %}            

    redis:
        image: "redis:alpine"
        container_name: {{PROJECT}}-redis
        restart: unless-stopped
        tty: true
        # Connecting at browser
        # redis://username:password@87.251.78.17:6973/0
        # username: default
        # password: ${REDIS_PASSWORD}
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
        ports:
            #    - 87.251.78.17:6973:6379
            - 6379:6379
        volumes:
            - redis-{{PROJECT}}:/var/lib/redis
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            - app-network-{{PROJECT}}            

networks:
    app-network-{{PROJECT}}:
        driver: bridge
    nginxproxyman:
        external: true
        name: nginxproxyman
    sqldev-backend:
        external: true
        name: sqldev-backend

volumes:
    redis-{{PROJECT}}:
        driver: local
        name: redis-{{PROJECT}}
    {{DB_VOLUME}}:
        driver: local
        name: {{DB_VOLUME}}

